# Generated by Django 2.1.15 on 2020-01-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20200107_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='server_count',
            field=models.IntegerField(),
        ),
    ]
