# Generated by Django 2.1.15 on 2020-01-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20200107_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
