# Generated by Django 2.1.15 on 2020-01-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20200107_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
